######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 1 22:12:23 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += \
    widget.h \
    mainwindow.h
SOURCES += main.cpp \
    widget.cpp \
    mainwindow.cpp
